# [START app]
runtime: nodejs
env: flex

# env_variables:
#   MYSQL_DNS: mysql:unix_socket=/cloudsql/tough-entry-330119:us-central1:db-sql;dbname=DATABASE
#   MYSQL_USER: main
#   MYSQL_PASSWORD: 'password1234'

# env_variables:
#   NPM_CONFIG_PRODUCTION:  false
#   NPM_CONFIG_LOGLEVEL:  error
#   NODE_VERBOSE: false
#   NODE_ENV: development
#   NODE_MODULES_CACHE: true